// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bssbnqrhqkfazdvybsto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzc2JucXJocWtmYXpkdnlic3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzQxODIsImV4cCI6MjA2ODYxMDE4Mn0.3Fa0PboX3pf00ylHdJvl9ppXa2djVludz3Uya9fAD-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});